### PR TITLE
:arrow_up: bumped @equinor/eds-core-react to get datepicker

### PR DESCRIPTION
**Pull request by Brynjulf**
Also updated vs code setting to not remove end of line in json files

### CODE REVIEW

**Comment by mariush2** [comment]
Have you re-run the tests? I see they're failing now

**Comment by eddiman** [comment]
What's the status on this?

**Comment by mariush2** [comment]
@eddiman Upgrading causes tests to break so either we need to look into fixing the tests or close this PR for now

**Comment by Brynjulf** [comment]
The datepicker from eds is missing features that we want to have before we actually use this, so we were having offline discussions surrounding how and where we should solve this, that's why i haven't done anything on this since. We can close this

**Pull request closed without merging**
