### PR TITLE
:bug: avoid silent auth crashes

### PR DESCRIPTION
**Pull request by Brynjulf**
I have not tested that this works, I don't know of a good way to test this so if anyone has any good ideas I am all ears.

### CODE REVIEW

**Comment by mariush2** [comment]
Best way to test is by using the bulld and use script

**Comment by Brynjulf** [comment]
> Best way to test is by using the bulld and use script

Sure, but this is related to the silent auth to get a new access token after the initial one expires

**Comment by mariush2** [comment]
Did work to edit the localstorage to trigger the error?

**Comment by Brynjulf** [comment]
> Did work to edit the localstorage to trigger the error?

Unfortunately, no. I tried to remove only the access token, then the access toke and reference id, then all msal related key/value pairs, and finally the entire local storage. Nothing triggered the error :/

Also we copy the auth.html file over implicitly when running docker, it is located in the `public` folder which we copy over

**Review by mariush2 — APPROVED** [review]

**Pull request merged**
